import type {Metadata} from "next";
import "../(main)/globals.scss";
import "../(main)/config.css";

import {
    dehydrate,
    HydrationBoundary,
} from '@tanstack/react-query'
import {getQueryClient} from "@/utils/get-query-client";
import ClientReactQueryProvider from "@/utils/reactQueryProvider-client";
import ToastProvider from "@/utils/react-toastify-client";
import ModalContext from "@/context/modal";
import Auth from "@/context/authentication";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const bYekan = localFont({
    src: [
        {
            path: "../../fonts/YekanBakhFaNum-Regular.woff",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../fonts/YekanBakhFaNum-Bold.woff",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-bYekan",
    display: "swap",
});
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const hour = new Date().getHours();
    const theme = (hour >= 20 || hour < 6) ? 'dark' : 'light';
    const queryClient = getQueryClient()
    return (
        <html dir="rtl" lang="fa-IR" className={theme} data-theme={theme}>
        {/*<head>*/}
        {/*    <script*/}
        {/*        dangerouslySetInnerHTML={{*/}
        {/*            __html: `*/}
        {/*      (function() {*/}
        {/*        const hour = new Date().getHours();*/}
        {/*        const theme = (hour >= 20 || hour < 6) ? 'dark' : 'light';*/}
        {/*        document.documentElement.classList.add(theme);*/}
        {/*        document.documentElement.setAttribute('data-theme', theme);*/}
        {/*      })();*/}
        {/*    `,*/}
        {/*        }}*/}
        {/*    />*/}
        {/*</head>*/}
        <body className={`${bYekan.variable} rtl main font-sans`}>
        <ClientReactQueryProvider>
            <ToastProvider>
                <Auth>
                    <ModalContext>
                        <HydrationBoundary state={dehydrate(queryClient)}>
                            <main>
                                {children}
                            </main>
                        </HydrationBoundary>
                    </ModalContext>
                </Auth>
            </ToastProvider>
        </ClientReactQueryProvider>
        </body>
        </html>
    );
}
