import type {Metadata} from "next";
import UserPanelSideBar from "@/layout/userpanel/userPanelSideBar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <div className={"userPanel flex-col lg:flex-row flex gap-4 container my-7"}>
            {/*<div className="userPanel__bg"/>*/}
            <UserPanelSideBar/>
            <div className={"flex-1 h-max min-w-0 overflow-x-auto bg-base-300 rounded-xl p-4"}>
                {children}
            </div>
        </div>
    );
}
